"""Add EmailDigest and DigestItem tables

Revision ID: afa3b01f72d7
Revises: cc2ba3d78bdb
Create Date: 2026-09-17 11:27:37.963749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa3b01f72d7'
down_revision: Union[str, Sequence[str], None] = 'cc2ba3d78bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_digest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('digest_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_digest_id'), 'email_digest', ['id'], unique=False)
    op.create_table('digest_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('requires_action', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['digest_id'], ['email_digest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digest_item_id'), 'digest_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digest_item_id'), table_name='digest_item')
    op.drop_table('digest_item')
    op.drop_index(op.f('ix_email_digest_id'), table_name='email_digest')
    op.drop_table('email_digest')
    # ### end Alembic commands ###
